version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./app:/app
    ports:
      - '3000:3000'
    depends_on:
      - redis
