version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .

      target: development
    volumes:
      - .:/usr/src/app

    command: npm run start:dev
    ports:
      - 3001:3010

    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data
volumes:
  redis:
    driver: local
